---
- name: Ensure pipx is installed
  ansible.builtin.package:
    name: pipx
    state: present
  tags:
    - pipx

- name: Ensure pipx path is configured
  ansible.builtin.command: pipx ensurepath
  changed_when: false
  tags:
    - pipx

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop: "{{ pipx_packages }}"
  tags:
    - pipx
