---
- name: Detect if host is an Apple MacBook
  ansible.builtin.shell: "cat /sys/devices/virtual/dmi/id/product_name || echo 'Unknown'"
  register: mac_model
  changed_when: false
  tags:
    - systemd
    - macbook
    - backlight

- name: Set fact if Apple MacBook
  ansible.builtin.set_fact:
    is_macbook: "{{ 'MacBook' in mac_model.stdout }}"
  tags:
    - systemd
    - macbook
    - backlight

- name: Create wifi-reset systemd sleep script
  #become: true
  ansible.builtin.copy:
    dest: /usr/lib/systemd/system-sleep/wifi-reset
    content: |
      #!/bin/sh
      case "$1" in
        pre)
          # Before sleep
          nmcli networking off
          ;;
        post)
          # After wake
          nmcli networking on
          ;;
      esac
    mode: '0755'
  when: is_macbook | default(false)
  tags:
    - systemd
    - macbook

- name: Check if acpi_backlight=native is already set
  ansible.builtin.shell:
    cmd: grep -q "acpi_backlight=native" /proc/cmdline
  register: backlight_need
  changed_when: false
  failed_when: false
  when: is_macbook | default(false)
  tags:
    - systemd
    - macbook
    - backlight

- name: Fix MacBook backlight (use Intel native driver instead of buggy ACPI)
  ansible.builtin.command:
    cmd: grubby --update-kernel=ALL --args="acpi_backlight=native"
  when:
    - is_macbook | default(false)
    - backlight_need.rc != 0
  tags:
    - systemd
    - macbook
    - backlight
